library(tidyverse)
library(dplyr)
library(tidycensus)
library(rsq)



#the data being used for each model and regression
WORKING_DATA <- read_csv("data/COMBINED_DATA_10.CSV")


#run the first two hashtag things

#### MODEL WITH ONLY SIGNIFICANT VALUES ####


# TURN STATE EXPANDED MEDICAID INTO A USEABLE VALUE
if (!is.factor(WORKING_DATA$STATE_EXPANDED_MEDICAID) ||
    !all(levels(WORKING_DATA$STATE_EXPANDED_MEDICAID) %in% c("NOTEXPANDED", "EXPANDED"))) {
  
  # Ensure numeric version exists or is correctly set
  WORKING_DATA$STATE_EXPANDED_MEDICAID_NUM <- ifelse(
    WORKING_DATA$STATE_EXPANDED_MEDICAID %in% c(TRUE, 1), 1,
    ifelse(WORKING_DATA$STATE_EXPANDED_MEDICAID %in% c(FALSE, 0), 0, NA)
  )
  
  # Convert to factor with labels
  WORKING_DATA$STATE_EXPANDED_MEDICAID <- factor(
    WORKING_DATA$STATE_EXPANDED_MEDICAID_NUM,
    levels = c(0, 1),
    labels = c("NOTEXPANDED", "EXPANDED")
  )
}


if (!is.factor(WORKING_DATA$MEDICAID_WORK_REQUIREMENT) ||
    !all(levels(WORKING_DATA$MEDICAID_WORK_REQUIREMENT) %in% c("NOT-REQUIRED", "REQUIRED"))) {
  
  WORKING_DATA$MEDICAID_WORK_REQUIREMENT <- ifelse(
    WORKING_DATA$MEDICAID_WORK_REQUIREMENT %in% c(TRUE, 1), 1,
    ifelse(WORKING_DATA$MEDICAID_WORK_REQUIREMENT %in% c(FALSE, 0), 0, NA)
  )
  
  WORKING_DATA$MEDICAID_WORK_REQUIREMENT <- factor(
    WORKING_DATA$MEDICAID_WORK_REQUIREMENT,
    levels = c(0, 1),
    labels = c("NOT-REQUIRED", "REQUIRED")
  )
}

unique(WORKING_DATA$STATE_EXPANDED_MEDICAID)
str(WORKING_DATA$STATE_EXPANDED_MEDICAID)
unique(WORKING_DATA$MEDICAID_WORK_REQUIREMENT)
str(WORKING_DATA$MEDICAID_WORK_REQUIREMENT)

# FORMULA
significant_values_model_formula <- (COST_UNCOMP/TOT_COST) ~
  HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE +
  HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE +
  HI_COVERAGE_35TO64_1HITYPE_MEDICAID +
  HI_COVERAGE_35TO64_1HITYPE_TRICARE +
  HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID +
  HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY +
  HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY + 
  HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE +
  HI_COVERAGE_35TO64_NOINSURANCE +
  HI_COVERAGE_19TO34_NOINSURANCE +
  HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED +
  HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE +
  HI_COVERAGE_19TO34_1HITYPE_MEDICAID +
  STATE_EXPANDED_MEDICAID +  
  MEDICAID_WORK_REQUIREMENT

#  + HOUSEHOLD_INCOME_50TO100_PERCENT + HOUSEHOLD_INCOME_100TO200_PERCENT +
# HOUSEHOLD_INCOME_30BELOW_PERCENT

# MODEL 
glm_model_for_significan_values <- glm(
  formula = significant_values_model_formula,
  family = gaussian(link = "identity"),
  data = WORKING_DATA
)

# VIEW RESULTS
summary(glm_model_for_significan_values)

rsq(glm_model_for_significan_values)





#### Regression Prediction for Significant Values ####

predict_uncomp_cost_with_significant_values_model <- function(ccn = "360003") 
{
  
  
  
  target_row <- WORKING_DATA[WORKING_DATA$PROVIDER_CCN == ccn, ]
  
  # Create a prediction data frame
  TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION <- data.frame(
    HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE = target_row$HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICARE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICAID = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICAID,
    HI_COVERAGE_35TO64_1HITYPE_TRICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_TRICARE,
    HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE,
    HI_COVERAGE_35TO64_NOINSURANCE = target_row$HI_COVERAGE_35TO64_NOINSURANCE,
    HI_COVERAGE_19TO34_NOINSURANCE = target_row$HI_COVERAGE_19TO34_NOINSURANCE,
    HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED = target_row$HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED,
    HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICARE = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICARE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICAID = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICAID,
    HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE,
    STATE_EXPANDED_MEDICAID = target_row$STATE_EXPANDED_MEDICAID,
    MEDICAID_WORK_REQUIREMENT = target_row$MEDICAID_WORK_REQUIREMENT
  )
  
  
  # Predict proportion
  predicted_proportion <- predict(glm_model_for_significan_values, newdata = TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION)
  
  # Return estimated cost
  
  return(predicted_proportion)
}










# dont move throught the wrong programs you dumbass




#### Regression Prediction Significant values with BBB predictions ####

predict_with_significant_values_the_bbb_change <- function(ccn = "360003",
                                                           HI_35TO64_MEDICAID = "10", 
                                                           HI_19TO34_MEDICAID = "50", 
                                                           HI_19TO34_DIRECT_PURCHASE = "-90")
{
  HI_35TO64_MEDICAID <- (as.numeric(HI_35TO64_MEDICAID)/100)
  HI_19TO34_MEDICAID <- (as.numeric(HI_19TO34_MEDICAID)/100)
  HI_19TO34_DIRECT_PURCHASE <- (as.numeric(HI_19TO34_DIRECT_PURCHASE)/100)
  
  HI_MEDICAREANDMEDICAID <- -1
  
  
  target_row <- WORKING_DATA[WORKING_DATA$PROVIDER_CCN == ccn, ]
  
  # Create a prediction data frame
  TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION <- data.frame(
    HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE = target_row$HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICARE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICAID = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICAID,
    HI_COVERAGE_35TO64_1HITYPE_TRICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_TRICARE,
    HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE,
    HI_COVERAGE_35TO64_NOINSURANCE = target_row$HI_COVERAGE_35TO64_NOINSURANCE,
    HI_COVERAGE_19TO34_NOINSURANCE = target_row$HI_COVERAGE_19TO34_NOINSURANCE,
    HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED = target_row$HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED,
    HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICARE = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICARE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICAID = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICAID,
    HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE,
    STATE_EXPANDED_MEDICAID = target_row$STATE_EXPANDED_MEDICAID,
    MEDICAID_WORK_REQUIREMENT = target_row$MEDICAID_WORK_REQUIREMENT
  )
  TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION <- TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION %>%
    
  
    mutate(HI_COVERAGE_35TO64_NOINSURANCE =  HI_COVERAGE_35TO64_NOINSURANCE - (HI_35TO64_MEDICAID *  HI_COVERAGE_35TO64_1HITYPE_MEDICAID) 
           - (HI_MEDICAREANDMEDICAID * HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID)) %>%
    
    mutate(HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID = HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID * (1 - HI_MEDICAREANDMEDICAID)) %>%
    
    
    mutate(HI_COVERAGE_35TO64_1HITYPE_MEDICAID = HI_COVERAGE_35TO64_1HITYPE_MEDICAID * (1 - HI_35TO64_MEDICAID))%>%
    
    mutate(HI_COVERAGE_19TO34_NOINSURANCE = HI_COVERAGE_19TO34_NOINSURANCE - (HI_COVERAGE_19TO34_1HITYPE_MEDICAID * HI_19TO34_MEDICAID) 
           - (HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE * HI_19TO34_DIRECT_PURCHASE)) %>%
    
    
    mutate(HI_COVERAGE_19TO34_1HITYPE_MEDICAID =  HI_COVERAGE_19TO34_1HITYPE_MEDICAID * (1 - HI_19TO34_MEDICAID)) %>%
    
    
    mutate(HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE = HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE * (1 - HI_19TO34_DIRECT_PURCHASE))
    
  # Predict proportion
  predicted_proportion <- predict(glm_model_for_significan_values, newdata = TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION)
  
  # Return estimated cost
  
  return(predicted_proportion)
}








#different model watch out 






# DONT GO ANY FURTHER THAN THIS 




##### stop here #####
#### THE WHOLE GLM MODEL ####





# TURN STATE EXPANDED MEDICAID INTO A USEABLE VALUE
if (!is.factor(WORKING_DATA$STATE_EXPANDED_MEDICAID) ||
    !all(levels(WORKING_DATA$STATE_EXPANDED_MEDICAID) %in% c("NOTEXPANDED", "EXPANDED"))) {
  
  # Ensure numeric version exists or is correctly set
  WORKING_DATA$STATE_EXPANDED_MEDICAID_NUM <- ifelse(
    WORKING_DATA$STATE_EXPANDED_MEDICAID %in% c(TRUE, 1), 1,
    ifelse(WORKING_DATA$STATE_EXPANDED_MEDICAID %in% c(FALSE, 0), 0, NA)
  )
  
  # Convert to factor with labels
  WORKING_DATA$STATE_EXPANDED_MEDICAID <- factor(
    WORKING_DATA$STATE_EXPANDED_MEDICAID_NUM,
    levels = c(0, 1),
    labels = c("NOTEXPANDED", "EXPANDED")
  )
}


if (!is.factor(WORKING_DATA$MEDICAID_WORK_REQUIREMENT) ||
    !all(levels(WORKING_DATA$MEDICAID_WORK_REQUIREMENT) %in% c("NOT-REQUIRED", "REQUIRED"))) {
  
  WORKING_DATA$MEDICAID_WORK_REQUIREMENT <- ifelse(
    WORKING_DATA$MEDICAID_WORK_REQUIREMENT %in% c(TRUE, 1), 1,
    ifelse(WORKING_DATA$MEDICAID_WORK_REQUIREMENT %in% c(FALSE, 0), 0, NA)
  )
  
  WORKING_DATA$MEDICAID_WORK_REQUIREMENT <- factor(
    WORKING_DATA$MEDICAID_WORK_REQUIREMENT,
    levels = c(0, 1),
    labels = c("NOT-REQUIRED", "REQUIRED")
  )
}

unique(WORKING_DATA$STATE_EXPANDED_MEDICAID)
str(WORKING_DATA$STATE_EXPANDED_MEDICAID)
unique(WORKING_DATA$MEDICAID_WORK_REQUIREMENT)
str(WORKING_DATA$MEDICAID_WORK_REQUIREMENT)

# FORMULA
model_formula <- (COST_UNCOMP/TOT_COST) ~ 
  HI_COVERAGE_65UP +
  HI_COVERAGE_65UP_1HITYPE_EMPLOYERBASED +
  HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE +
  HI_COVERAGE_65UP_1HITYPE_MEDICARE +
  HI_COVERAGE_65UP_1HITYPE_TRICARE +
  HI_COVERAGE_65UP_1HITYPE_VACARE +
  HI_COVERAGE_65UP_2UPHITYPE_EMPLOYERANDMEDICARE +
  HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE +
  HI_COVERAGE_65UP_2UPHITYPE_PRIVATEONLY +
  HI_COVERAGE_65UP_2UPHITYPE_PUBLICONLY + 
  HI_COVERAGE_65UP_2UPHITYPE_OTHERCOVERAGE +
  HI_COVERAGE_65UP_NOINSURANCE +
  HI_COVERAGE_35TO64 +
  HI_COVERAGE_35TO64_1HITYPE_EMPLOYERBASED +
  HI_COVERAGE_35TO64_1HITYPE_DIRECTPURCHASE +
  HI_COVERAGE_35TO64_1HITYPE_MEDICARE +
  HI_COVERAGE_35TO64_1HITYPE_MEDICAID +
  HI_COVERAGE_35TO64_1HITYPE_TRICARE +
  HI_COVERAGE_35TO64_1HITYPE_VACARE +
  HI_COVERAGE_35TO64_2UPHITYPE_EMPLOYERANDMEDICARE +
  HI_COVERAGE_35TO64_2UPHITYPE_DIRECTANDMEDICARE +
  HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID +
  HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY +
  HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY + 
  HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE +
  HI_COVERAGE_35TO64_NOINSURANCE +
  HI_COVERAGE_19TO34 +
  HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED +
  HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE +
  HI_COVERAGE_19TO34_1HITYPE_MEDICARE +
  HI_COVERAGE_19TO34_1HITYPE_MEDICAID +
  HI_COVERAGE_19TO34_1HITYPE_TRICARE +
  HI_COVERAGE_19TO34_1HITYPE_VACARE +
  HI_COVERAGE_19TO34_2UPHITYPE_EMPLOYERANDMEDICARE +
  HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID +
  HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY +
  HI_COVERAGE_19TO34_2UPHITYPE_PUBLICONLY + 
  HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE +
  HI_COVERAGE_19TO34_NOINSURANCE +
  STATE_EXPANDED_MEDICAID +  
  MEDICAID_WORK_REQUIREMENT

#  + HOUSEHOLD_INCOME_50TO100_PERCENT + HOUSEHOLD_INCOME_100TO200_PERCENT +
# HOUSEHOLD_INCOME_30BELOW_PERCENT

# MODEL 
glm_model <- glm(
  formula = model_formula,
  family = gaussian(link = "identity"),
  data = WORKING_DATA
)

# VIEW RESULTS
summary(glm_model)

rsq(glm_model)







#### Regression Prediction FOR WHOLE GLM MODEL ####

predict_uncomp_cost_with_whole_GLM_model <- function(ccn = "360003") 
{
  
  
  
  target_row <- WORKING_DATA[WORKING_DATA$PROVIDER_CCN == ccn, ]
  
  # Create a prediction data frame
  TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION <- data.frame(
    HI_COVERAGE_65UP = target_row$HI_COVERAGE_65UP,
    HI_COVERAGE_65UP_1HITYPE_EMPLOYERBASED = target_row$HI_COVERAGE_65UP_1HITYPE_EMPLOYERBASED,
    HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_65UP_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_65UP_1HITYPE_MEDICARE = target_row$HI_COVERAGE_65UP_1HITYPE_MEDICARE,
    HI_COVERAGE_65UP_1HITYPE_TRICARE = target_row$HI_COVERAGE_65UP_1HITYPE_TRICARE,
    HI_COVERAGE_65UP_1HITYPE_VACARE = target_row$HI_COVERAGE_65UP_1HITYPE_VACARE,
    HI_COVERAGE_65UP_2UPHITYPE_EMPLOYERANDMEDICARE = target_row$HI_COVERAGE_65UP_2UPHITYPE_EMPLOYERANDMEDICARE,
    HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE = target_row$HI_COVERAGE_65UP_2UPHITYPE_DIRECTANDMEDICARE,
    HI_COVERAGE_65UP_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_65UP_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_65UP_2UPHITYPE_PUBLICONLY = target_row$HI_COVERAGE_65UP_2UPHITYPE_PUBLICONLY, 
    HI_COVERAGE_65UP_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_65UP_2UPHITYPE_OTHERCOVERAGE,
    HI_COVERAGE_65UP_NOINSURANCE = target_row$HI_COVERAGE_65UP_NOINSURANCE,
    HI_COVERAGE_35TO64 = target_row$HI_COVERAGE_35TO64,
    HI_COVERAGE_35TO64_1HITYPE_EMPLOYERBASED = target_row$HI_COVERAGE_35TO64_1HITYPE_EMPLOYERBASED,
    HI_COVERAGE_35TO64_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_35TO64_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICARE,
    HI_COVERAGE_35TO64_1HITYPE_MEDICAID = target_row$HI_COVERAGE_35TO64_1HITYPE_MEDICAID,
    HI_COVERAGE_35TO64_1HITYPE_TRICARE = target_row$HI_COVERAGE_35TO64_1HITYPE_TRICARE,
    HI_COVERAGE_35TO64_1HITYPE_VACARE = target_row$HI_COVERAGE_35TO64_1HITYPE_VACARE,
    HI_COVERAGE_35TO64_2UPHITYPE_EMPLOYERANDMEDICARE = target_row$HI_COVERAGE_35TO64_2UPHITYPE_EMPLOYERANDMEDICARE,
    HI_COVERAGE_35TO64_2UPHITYPE_DIRECTANDMEDICARE = target_row$HI_COVERAGE_35TO64_2UPHITYPE_DIRECTANDMEDICARE,
    HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_35TO64_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY = target_row$HI_COVERAGE_35TO64_2UPHITYPE_PUBLICONLY,
    HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_35TO64_2UPHITYPE_OTHERCOVERAGE,
    HI_COVERAGE_35TO64_NOINSURANCE = target_row$HI_COVERAGE_35TO64_NOINSURANCE,
    HI_COVERAGE_19TO34 = target_row$HI_COVERAGE_19TO34,
    HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED = target_row$HI_COVERAGE_19TO34_1HITYPE_EMPLOYERBASED,
    HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE = target_row$HI_COVERAGE_19TO34_1HITYPE_DIRECTPURCHASE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICARE = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICARE,
    HI_COVERAGE_19TO34_1HITYPE_MEDICAID = target_row$HI_COVERAGE_19TO34_1HITYPE_MEDICAID,
    HI_COVERAGE_19TO34_1HITYPE_TRICARE = target_row$HI_COVERAGE_19TO34_1HITYPE_TRICARE,
    HI_COVERAGE_19TO34_1HITYPE_VACARE = target_row$HI_COVERAGE_19TO34_1HITYPE_VACARE,
    HI_COVERAGE_19TO34_2UPHITYPE_EMPLOYERANDMEDICARE = target_row$HI_COVERAGE_19TO34_2UPHITYPE_EMPLOYERANDMEDICARE,
    HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID = target_row$HI_COVERAGE_19TO34_2UPHITYPE_MEDICAREANDMEDICAID,
    HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY = target_row$HI_COVERAGE_19TO34_2UPHITYPE_PRIVATEONLY,
    HI_COVERAGE_19TO34_2UPHITYPE_PUBLICONLY = target_row$HI_COVERAGE_19TO34_2UPHITYPE_PUBLICONLY, 
    HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE = target_row$HI_COVERAGE_19TO34_2UPHITYPE_OTHERCOVERAGE,
    HI_COVERAGE_19TO34_NOINSURANCE = target_row$HI_COVERAGE_19TO34_NOINSURANCE,
    STATE_EXPANDED_MEDICAID = target_row$STATE_EXPANDED_MEDICAID,
    MEDICAID_WORK_REQUIREMENT = target_row$MEDICAID_WORK_REQUIREMENT
  )
  
  # Predict proportion
  predicted_proportion <- predict(glm_model, newdata = TOTAL_VARIABLES_DATA_FRAME_FOR_FUNCTION)
  
  # Return estimated cost
  
  return(list(
    predicted_proportion
    
  )
  )
}









